import { StyleSheet, Dimensions } from 'react-native';
import { ColorScheme } from '../../types';

const { width, height } = Dimensions.get('window');

export const createStyles = (colors: ColorScheme) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
    },
    floatingHeader: {
      position: 'absolute',
      top: 50,
      left: 0,
      right: 0,
      zIndex: 10,
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: 20,
    },
    headerButton: {
      width: 46,
      height: 46,
      borderRadius: 23,
      backgroundColor: colors.background,
      justifyContent: 'center',
      alignItems: 'center',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 8,
      elevation: 4,
    },
    badge: {
      position: 'absolute',
      right: -4,
      top: -4,
      minWidth: 22,
      height: 22,
      borderRadius: 11,
      backgroundColor: colors.primary,
      justifyContent: 'center',
      alignItems: 'center',
      paddingHorizontal: 6,
      borderWidth: 2,
      borderColor: colors.background,
    },
    badgeText: {
      color: '#FFFFFF',
      fontSize: 11,
      fontWeight: '700',
    },
    headerActions: {
      flexDirection: 'row',
      gap: 12,
    },
    scrollContent: {
      flexGrow: 1,
    },
    imageContainer: {
      width: '100%',
      height: height * 0.55,
      backgroundColor: colors.card,
    },
    image: {
      width: '100%',
      height: '100%',
    },
    imagePagination: {
      position: 'absolute',
      bottom: 20,
      left: 0,
      right: 0,
      flexDirection: 'row',
      justifyContent: 'center',
      gap: 8,
    },
    paginationDot: {
      width: 8,
      height: 8,
      borderRadius: 4,
      backgroundColor: colors.background,
      opacity: 0.5,
    },
    paginationDotActive: {
      opacity: 1,
      width: 24,
    },
    contentContainer: {
      backgroundColor: colors.background,
      borderTopLeftRadius: 32,
      borderTopRightRadius: 32,
      marginTop: -32,
      padding: 24,
      paddingBottom: 120,
    },
    categoryRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 12,
    },
    categoryBadge: {
      backgroundColor: colors.primary + '15',
      paddingHorizontal: 14,
      paddingVertical: 8,
      borderRadius: 20,
    },
    categoryText: {
      fontSize: 12,
      fontWeight: '700',
      color: colors.primary,
      textTransform: 'uppercase',
      letterSpacing: 0.5,
    },
    name: {
      fontSize: 26,
      fontWeight: '800',
      color: colors.text,
      marginBottom: 8,
      lineHeight: 34,
    },
    priceRow: {
      flexDirection: 'row',
      alignItems: 'baseline',
      marginBottom: 24,
    },
    price: {
      fontSize: 28,
      fontWeight: '800',
      color: colors.primary,
    },
    priceNote: {
      fontSize: 13,
      color: colors.textSecondary,
      marginLeft: 8,
    },
    section: {
      marginBottom: 24,
    },
    sectionTitle: {
      fontSize: 16,
      fontWeight: '700',
      color: colors.text,
      marginBottom: 12,
    },
    description: {
      fontSize: 15,
      color: colors.textSecondary,
      lineHeight: 24,
    },
    featuresGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 12,
    },
    featureItem: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.card,
      paddingHorizontal: 14,
      paddingVertical: 10,
      borderRadius: 12,
    },
    featureText: {
      fontSize: 13,
      color: colors.text,
      marginLeft: 8,
      fontWeight: '500',
    },
    footer: {
      position: 'absolute',
      bottom: 0,
      left: 0,
      right: 0,
      backgroundColor: colors.background,
      paddingHorizontal: 24,
      paddingTop: 16,
      paddingBottom: 32,
      borderTopWidth: 1,
      borderTopColor: colors.border,
    },
    footerContent: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 16,
    },
    priceContainer: {
      flex: 1,
    },
    priceLabel: {
      fontSize: 12,
      color: colors.textSecondary,
      marginBottom: 2,
    },
    footerPrice: {
      fontSize: 22,
      fontWeight: '800',
      color: colors.text,
    },
    addButton: {
      flex: 2,
      backgroundColor: colors.primary,
      borderRadius: 16,
      paddingVertical: 18,
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'center',
    },
    addButtonText: {
      color: '#FFFFFF',
      fontSize: 16,
      fontWeight: '700',
      marginLeft: 8,
    },
  });