import { Product } from '../types';

export const PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Rhode Peptide Lip Tint',
    price: 1950.00,
    image: require('../../assets/products/rhode.jpg'),
    category: 'Lip Tint',
    description: 'A sheer, buildable lip tint that melts onto lips for a glossy, plumped finish. Fragrance-free and highly hydrating with shea butter and peptides.',
  },
  {
    id: '2',
    name: 'Charlotte Tilbury Airbrush Flawless Finish Blurring & Setting Powder',
    price: 3600.00,
    image: require('../../assets/products/charlottetilburypowder.jpg'),
    category: 'Airbrush',
    description: 'An ultra-fine, silk-touch setting powder that blurs pores and imperfections. Features rose wax and almond oil to prevent caking. ',
  },
  {
    id: '3',
    name: 'Rhode Pocket Blush',
    price: 650.00,
    image: require('../../assets/products/rhodeblush.jpg'),
    category: 'Blush',
    description: 'A cream blush stick that gives a "pinch-of-color" glow. Lightweight, blendable, and designed to fit in your pocket for on-the-go touch-ups.',
  },
  {
    id: '4',
    name: 'Charlotte Tilbury Airbrush Flawless Setting Spray ',
    price: 2700.00,
    image: require('../../assets/products/charlottetilbury.jpg'),
    category: 'Setting Spray',
    description: 'A weightless, oil-free hydrating spray that primes and sets makeup for up to 16 hours without smudging or fading.',
  },
  {
    id: '5',
    name: 'ONE/SIZE On Til Dawn Setting Spray',
    price: 2750.00,
    image: require('../../assets/products/ossettingspray.jpg'),
    category: 'Setting Spray',
    description: 'An aerosol mattifying waterproof setting spray by Patrick Starrr. Known for its extreme hold and "blurring" matte finish. ',
  },
  {
    id: '6',
    name: 'Benefit Benetint',
    price: 950.00,
    image: require('../../assets/products/benefitbenetint.jpg'),
    category: 'Tint',
    description: 'The iconic rose-tinted lip and cheek stain. Provides a natural, see-through flush that is smudge-proof and long-wearing.',
  },
  {
    id: '7',
    name: 'Dior Backstage Glow Face Palette',
    price: 3950.00,
    image: require('../../assets/products/diorpalette.jpg'),
    category: 'Palette',
    description: 'A multi-use professional palette featuring four shades: highlighter, blush, and bronzer with pearlescent and metallic finishes.',
  },
  {
    id: '8',
    name: 'Benefit Preciselym My Brow Pencil',
    price: 1790.00,
    image: require('../../assets/products/benefitbrowpencil.jpg'),
    category: 'Brow Pencil',
    description: 'An ultra-fine eyebrow defining pencil that draws incredibly natural-looking, hair-like strokes. Includes a built-in spoolie.',
  },
  {
    id: '9',
    name: 'Nars Radiant Creamy Concealer',
    price: 2100.00,
    image: require('../../assets/products/narsconcealer.jpg'),
    category: 'Concealer',
    description: 'An award-winning concealer that provides medium-to-high buildable coverage with a natural, luminous finish.',
  },
  {
    id: '10',
    name: 'Kylie Jenner Cosmic Eau de Parfum',
    price: 5500.00,
    image: require('../../assets/products/kyliejennercosmic.jpg'),
    category: 'Perfume',
    description: 'A magnetic, skin-inspired scent with notes of star jasmine, blood orange, golden amber, and vanilla musk.',
  },
  {
    id: '11',
    name: 'Rhode Glazing Milk',
    price: 2400.00,
    image: require('../../assets/products/rhodeglazingmilk.jpg'),
    category: 'Essence',
    description: 'A lightweight, nutrient-rich ceramide essence that boosts the skin barrier and provides immediate hydration for a "glazed" finish.',
  },
  {
    id: '12',
    name: 'Rhode Glazing Mist',
    price: 3100.00,
    image: require('../../assets/products/rhodeglazingmist.jpg'),
    category: 'Mist',
    description: 'A refreshing, hydrating face mist powered by Ectoin and Hyaluronic Acid to prep skin or set makeup with a dewy glow.',
  },
  {
    id: '13',
    name: 'Hourglass Ambient Lighting Edit (Swan)',
    price: 5600.00,
    image: require('../../assets/products/hourglassswan.jpg'),
    category: 'Palette',
    description: 'A limited-edition 6-pan face palette (Holiday Unlocked collection) featuring finishing powders, blush, and highlighter for a seamless, lit-from-within glow.',
  },
  {
    id: '14',
    name: 'Tarte Shape Tape Concealer',
    price: 2100.00,
    image: require('../../assets/products/tarteconcealer.jpg'),
    category: 'Concealer',
    description: 'The "holy grail" full-coverage concealer known for its matte finish and 16-hour wear. Perfect for blurring imperfections and contouring.',
  },
  {
    id: '15',
    name: 'Gucci Flora',
    price: 7500.00,
    image: require('../../assets/products/gucciflora.jpg'),
    category: 'Perfume',
    description: 'A joyful floral signature built around the Gardenia flower, blended with solar Jasmine and Pear Blossom.',
  },
  {
    id: '16',
    name: 'Tom Ford Vanilla Sex',
    price: 16500.00,
    image: require('../../assets/products/tomfordvanillasex.jpg'),
    category: 'Perfume',
    description: 'An ultra-luxurious, warm, and spicy gourmand fragrance featuring a dual-tincture of Vanilla with notes of Sandalwood.',
  },
  {
    id: '17',
    name: 'Parfums de Marly Delina',
    price: 18500.00,
    image: require('../../assets/products/pdmdelina.jpg'),
    category: 'Perfume',
    description: 'A viral, high-end floral bouquet dominated by Turkish Rose, Lychee, and Rhubarb. Sophisticated and feminine.',
  },
  {
    id: '18',
    name: 'CH Good Girl Blush',
    price: 8800.00,
    image: require('../../assets/products/chgoodgirl.jpg'),
    category: 'Perfume',
    description: 'A fresh, powdery reinvention of the iconic stiletto fragrance, featuring double Vanilla and Ylang-Ylang.',
  },
  {
    id: '19',
    name: 'Billie Eilish (Eilish No. 1)',
    price: 4800.00,
    image: require('../../assets/products/billieeilish.jpg'),
    category: 'Perfume',
    description: 'A cozy, ambery gourmand scent with notes of sugared petals, creamy vanilla, and warm musks.',
  },
  {
    id: '20',
    name: 'YSL Libre Eau de Parfum',
    price: 7500.00,
    image: require('../../assets/products/ysllibre.jpg'),
    category: 'Perfume',
    description: 'A "Grand Floral" fragrance that balances the sensuality of Orange Blossom with the coolness of Lavender.',
  },

];